---
plugins:
  - jest
  - babel

env:
  node: true
  jest/globals: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0

  - name: ESLint Action
  uses: hallee/eslint-action@1.0.1
